language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
branches:
  only:
  - master
notifications:
  slack:
    secure: Wu3Z1BrvPgIrIDgwC/+3143SXxd0POAxwE84ZN14/X7Dd26OvCnkv+vQdCFQDr3C+hKIxFDava414Jw5qte1JUIEQIt3E5RFlIte4SMvkC3ukoYXsqTAipj4KT9U8fK4YCJuGju0sltFRQ9zXFV4s4Q+paFIMSLp1K4KkD7ycrkSJ9Y+8/mw3/460XOfesTBuFm670TR6v5c0A5d2yKoADbv0URwXH5LPBbaF8BCYbZITXm9q827eneBDcF3b0aivJTyKzO6W9nSXUH1F9ditz3jwS+EPA9oRqMHNfHUBUQDv6b2sXPUN6b3pkkiSV9M+CSmcx1xXQOi0MUyNpws/TTt2cSEgJszfDOpcesT9IgxexJ1t7fwGMxT1iyyZFIuiXhsWrZxF2hCZ/gfCmuimFibR3ExFTIVpSzQ1uznLq6Uzjr9CN6JPnffM4t6Wkpk9EAIETG78NkQJO1sJa4f8hNApS+HGsQZ6H0IudojLkktIOiN59nB05S1TvdaNRFMQLjhfobktRjfzzfLAzPruJynsHraO54ThHeRJlGnCpsUMHTETGnURRs+QiiN1peLiyT1Gw/BwyOF2/MAjAuoyKqlyMIPk4rdXsBD2b/dkVMD0CP54Nr7LJt75p63kQbGgcakkc7MQ+8fAtxkaxnvmDSGXealQOm9PfEvYJx5OUI=
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  strategy: git
  app:
    master: thesismarket
  api_key:
    secure: hhMn/TSWy3Dds4jkDJlH0rKpu3Fm4vDJfqu58eyDPvURxZBS0KshtZxwZLogYh1Ubb1gKQYhv8Kkg1j8CjCJQuLRORqhKwRFFkXt4TpB9olHiRPyVuEwZSWXzKwwDCk7Efw9ILPug1L2l11YyEYr5c399J2s5bW33IU/KH1uMXUgn5Ho951ybMHjbuujYQDrpT9z856jR7tL+mbmaDX8rySF2e5hR6VFR3ly16DPbwDDFUDmxTr0vNwWWHXYa36rz4tocUZSzLox/+Zf2Ktha34v+PTosytKOaojB5Nw5zWs+NgL7lH9vDzuRPpPQ9A7HMGqpnw9xG2v2bvBKr658ZCd4+sS5jKMzN66uFzq/BN1pMUFCnqp7hexuzCfQiqo0QHUueYv8NC8lPx5Oy6smIP0yPUTKS9NgKxprwtZET0xwRaKqVFIpTSnsFzbMwka6o02tDu6YY9UsbyiWOsJIUnwXyeX8sz72rTFuv6QSDB4NVUT3dkPeK3Y/zHuXwOzbIV5fC7sI71MVdA40tsTKX3/LwuDbq9mVB+CUd4h8KduEbUtp+8qnKAhuauQFqYgQhHjzVdvB0Luh4pSXs7M/ELwC3DXYO/7cnpjeP9P3OJ5O9kEagwvpHWyUVtm7R+aDa70566eaB9LaqAJ5h/aY7TKZfb9Milx38OFjV1DyrU=
